# Generated by Django 6.0.4 on 2026-04-10 20:31

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
    ]

    operations = [
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('password', models.CharField(max_length=128, verbose_name='password')),
                ('last_login', models.DateTimeField(blank=True, null=True, verbose_name='last login')),
                ('is_superuser', models.BooleanField(default=False, help_text='Designates that this user has all permissions without explicitly assigning them.', verbose_name='superuser status')),
                ('email', models.EmailField(max_length=254, unique=True)),
                ('name', models.CharField(max_length=255)),
                ('birth_date', models.DateField()),
                ('gender', models.CharField(choices=[('male', 'Male'), ('female', 'Female'), ('notgiven', 'Not given')], default='notgiven', max_length=10)),
                ('avatar_url', models.URLField(blank=True, null=True)),
                ('interests', models.JSONField(blank=True, default=list)),
                ('city_settlement', models.CharField(blank=True, max_length=255, null=True)),
                ('city_region', models.CharField(blank=True, max_length=255, null=True)),
                ('city_country', models.CharField(blank=True, max_length=255, null=True)),
                ('city_latitude', models.FloatField(blank=True, null=True)),
                ('city_longitude', models.FloatField(blank=True, null=True)),
                ('city_title', models.CharField(blank=True, max_length=255, null=True)),
                ('show_avatar', models.BooleanField(default=True)),
                ('show_gender', models.BooleanField(default=True)),
                ('show_city_place', models.BooleanField(default=True)),
                ('show_interests', models.BooleanField(default=True)),
                ('show_birth_date', models.BooleanField(default=False)),
                ('show_attendance_history', models.BooleanField(default=True)),
                ('show_reviews', models.BooleanField(default=True)),
                ('is_active', models.BooleanField(default=True)),
                ('is_staff', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('deleted_at', models.DateTimeField(blank=True, null=True)),
                ('groups', models.ManyToManyField(blank=True, help_text='The groups this user belongs to. A user will get all permissions granted to each of their groups.', related_name='user_set', related_query_name='user', to='auth.group', verbose_name='groups')),
                ('user_permissions', models.ManyToManyField(blank=True, help_text='Specific permissions for this user.', related_name='user_set', related_query_name='user', to='auth.permission', verbose_name='user permissions')),
            ],
            options={
                'db_table': 'users',
            },
        ),
    ]
