# Generated by Django 6.0.4 on 2026-04-10 20:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='rating',
            field=models.FloatField(default=0.0),
        ),
    ]
