# Generated by Django 6.0.4 on 2026-04-12 20:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0003_qrtoken'),
    ]

    operations = [
        migrations.RenameField(
            model_name='user',
            old_name='show_city_place',
            new_name='show_city',
        ),
    ]
