# Generated by Codex on 2026-05-03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0005_remove_user_avatar_url_user_avatar_file'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='show_avatar',
        ),
        migrations.RemoveField(
            model_name='user',
            name='show_gender',
        ),
        migrations.RemoveField(
            model_name='user',
            name='show_city',
        ),
        migrations.RemoveField(
            model_name='user',
            name='show_interests',
        ),
        migrations.RemoveField(
            model_name='user',
            name='show_attendance_history',
        ),
        migrations.RemoveField(
            model_name='user',
            name='show_reviews',
        ),
    ]
