# Generated by Django 6.0.4 on 2026-05-15 23:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("users", "0006_remove_privacy_flags"),
    ]

    operations = [
        migrations.AddField(
            model_name="user",
            name="about_me",
            field=models.TextField(blank=True, max_length=1000, null=True),
        ),
        migrations.AddField(
            model_name="user",
            name="social_link",
            field=models.URLField(blank=True, max_length=500, null=True),
        ),
    ]
