# Generated by Django 6.0.4 on 2026-04-10 22:01

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Activity',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255)),
                ('description', models.TextField()),
                ('category_id', models.CharField(max_length=100)),
                ('subcategory_id', models.CharField(blank=True, max_length=100, null=True)),
                ('format', models.CharField(choices=[('online', 'Online'), ('offline', 'Offline')], max_length=10)),
                ('status', models.CharField(choices=[('active', 'Active'), ('cancelled', 'Cancelled')], default='active', max_length=10)),
                ('location_latitude', models.FloatField()),
                ('location_longitude', models.FloatField()),
                ('location_address', models.CharField(max_length=500)),
                ('location_name', models.CharField(blank=True, max_length=255, null=True)),
                ('location_settlement', models.CharField(blank=True, max_length=255, null=True)),
                ('start_at', models.DateTimeField()),
                ('end_at', models.DateTimeField()),
                ('time_zone', models.CharField(default='UTC', max_length=100)),
                ('pref_gender', models.CharField(blank=True, choices=[('male', 'Male'), ('female', 'Female')], max_length=10, null=True)),
                ('pref_age_from', models.IntegerField(blank=True, null=True)),
                ('pref_age_to', models.IntegerField(blank=True, null=True)),
                ('pref_level', models.CharField(blank=True, choices=[('beginner', 'Beginner'), ('intermediate', 'Intermediate'), ('advanced', 'Advanced')], max_length=20, null=True)),
                ('pref_max_participants', models.IntegerField(blank=True, null=True)),
                ('requires_approval', models.BooleanField(default=False)),
                ('photo_file_ids', models.JSONField(blank=True, default=list)),
                ('price', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('cancelled_at', models.DateTimeField(blank=True, null=True)),
                ('organizer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='organized_activities', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'activities',
                'ordering': ['-created_at'],
            },
        ),
    ]
