# Generated by Django 6.0.4 on 2026-04-16 20:15

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('activities', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='activity',
            options={'ordering': ['-created_at'], 'verbose_name': 'Activity', 'verbose_name_plural': 'Activities'},
        ),
        migrations.CreateModel(
            name='SavedActivity',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('saved_at', models.DateTimeField(auto_now_add=True)),
                ('activity', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='saved_by', to='activities.activity')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='saved_activities', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'saved_activities',
                'unique_together': {('user', 'activity')},
            },
        ),
    ]
