# Generated by Django 6.0.4 on 2026-04-16 22:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('activities', '0002_alter_activity_options_savedactivity'),
    ]

    operations = [
        migrations.AddField(
            model_name='activity',
            name='location_country',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='activity',
            name='location_region',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
