# Generated by Django 6.0.4 on 2026-04-23 13:42

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('activities', '0003_activity_location_country_activity_location_region'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='UserActivityFeedEvent',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type', models.CharField(choices=[('created', 'Created'), ('attended', 'Attended'), ('rated', 'Rated'), ('cancelled', 'Cancelled'), ('leaved', 'Leaved'), ('joined', 'Joined'), ('missed', 'Missed')], max_length=20)),
                ('occurred_at', models.DateTimeField()),
                ('metadata', models.JSONField(blank=True, default=dict)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('activity', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='feed_events', to='activities.activity')),
                ('actor_user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='actor_feed_events', to=settings.AUTH_USER_MODEL)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='activity_feed_events', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'user_activity_feed_events',
                'ordering': ['-occurred_at'],
            },
        ),
    ]
