# Generated by Django 6.0.4 on 2026-05-08 14:37

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('activities', '0004_useractivityfeedevent'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddIndex(
            model_name='activity',
            index=models.Index(fields=['status', 'start_at'], name='activities_status_c2e099_idx'),
        ),
        migrations.AddIndex(
            model_name='activity',
            index=models.Index(fields=['category_id'], name='activities_categor_19fdbd_idx'),
        ),
        migrations.AddIndex(
            model_name='activity',
            index=models.Index(fields=['location_settlement'], name='activities_locatio_bde861_idx'),
        ),
        migrations.AddIndex(
            model_name='savedactivity',
            index=models.Index(fields=['user', '-saved_at'], name='saved_activ_user_id_815a2a_idx'),
        ),
        migrations.AddIndex(
            model_name='useractivityfeedevent',
            index=models.Index(fields=['user', '-occurred_at'], name='user_activi_user_id_4fbcce_idx'),
        ),
    ]
