# Generated by Django 6.0.4 on 2026-05-10 23:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('activities', '0005_activity_activities_status_c2e099_idx_and_more'),
    ]

    operations = [
        migrations.RemoveIndex(
            model_name='useractivityfeedevent',
            name='user_activi_user_id_4fbcce_idx',
        ),
        migrations.DeleteModel(
            name='UserActivityFeedEvent',
        ),
    ]
