# Generated by Django 6.0.4 on 2026-05-14 16:21

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        (
            "activities",
            "0006_remove_useractivityfeedevent_user_activi_user_id_4fbcce_idx_and_more",
        ),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name="activity",
            name="kudago_id",
            field=models.IntegerField(blank=True, null=True, unique=True),
        ),
        migrations.AddField(
            model_name="activity",
            name="kudago_url",
            field=models.URLField(blank=True, max_length=500, null=True),
        ),
        migrations.AddField(
            model_name="activity",
            name="source",
            field=models.CharField(
                choices=[("user", "User"), ("kudago", "KudaGo")],
                default="user",
                max_length=10,
            ),
        ),
        migrations.AlterField(
            model_name="activity",
            name="organizer",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="organized_activities",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
    ]
