import random
import uuid
from datetime import UTC, datetime, timedelta

from locust import HttpUser, between, task


def iso_after(days, hours=0):
    return (datetime.now(UTC) + timedelta(days=days, hours=hours)).isoformat().replace('+00:00', 'Z')


class WeDoApiUser(HttpUser):
    wait_time = between(0.5, 2.0)

    def on_start(self):
        self.run_id = uuid.uuid4().hex[:12]
        self.email = f'loadtest_{self.run_id}@example.com'
        self.other_email = f'loadtest_organizer_{self.run_id}@example.com'
        self.password = 'LoadtestPass123'
        self.access_token = None
        self.refresh_token = None
        self.user_id = None
        self.other_user_id = None
        self.other_access_token = None
        self.activity_id = None
        self.qr_token = None

        self._register_primary_user()
        self._register_organizer_user()
        self._load_existing_activity()

    @property
    def auth_headers(self):
        return {'Authorization': f'Bearer {self.access_token}'}

    @property
    def organizer_headers(self):
        return {'Authorization': f'Bearer {self.other_access_token}'}

    def _register_payload(self, email, name):
        return {
            'name': name,
            'email': email,
            'password': self.password,
            'birthDate': '1998-05-20',
            'gender': 'notgiven',
            'city': {
                'settlement': 'Moscow',
                'region': 'Moscow',
                'country': 'Russia',
                'latitude': 55.751244,
                'longitude': 37.618423,
                'title': 'Moscow',
            },
            'interests': ['sport', 'board-games', 'music'],
            'privacy': {
                'showAvatar': True,
                'showGender': True,
                'showCity': True,
                'showInterests': True,
                'showBirthDate': False,
                'showAttendanceHistory': True,
                'showReviews': True,
            },
        }

    def _register_primary_user(self):
        response = self.client.post(
            '/auth/register',
            json=self._register_payload(self.email, f'loadtest User {self.run_id}'),
            name='Auth / Register primary',
        )
        if response.ok:
            data = response.json()
            self.access_token = data['tokens']['accessToken']
            self.refresh_token = data['tokens']['refreshToken']
            self.user_id = data['user']['id']

    def _register_organizer_user(self):
        response = self.client.post(
            '/auth/register',
            json=self._register_payload(self.other_email, f'loadtest Organizer {self.run_id}'),
            name='Auth / Register organizer',
        )
        if response.ok:
            data = response.json()
            self.other_access_token = data['tokens']['accessToken']
            self.other_user_id = data['user']['id']

    def _activity_payload(self, requires_approval=False):
        return {
            'title': f'loadtest Activity {self.run_id} {uuid.uuid4().hex[:6]}',
            'description': 'Activity generated by Locust load test.',
            'categoryId': 'sport',
            'subcategoryId': random.choice(['football', 'running', 'fitness']),
            'format': 'offline',
            'location': {
                'latitude': 55.751244,
                'longitude': 37.618423,
                'address': 'Moscow loadtest address',
                'name': 'Loadtest location',
                'settlement': 'Moscow',
                'region': 'Moscow',
                'country': 'Russia',
            },
            'startAt': iso_after(random.randint(3, 20)),
            'endAt': iso_after(random.randint(21, 30), hours=2),
            'timeZone': 'Europe/Moscow',
            'preferences': {
                'ageFrom': 18,
                'ageTo': 45,
                'level': 'beginner',
                'maxParticipants': 50,
            },
            'requiresApproval': requires_approval,
            'photoFileIds': [],
            'price': '0.00',
        }

    def _load_existing_activity(self):
        if not self.access_token:
            return
        response = self.client.get(
            '/activities?limit=1',
            headers=self.auth_headers,
            name='Activities / Pick existing for scenario',
        )
        if response.ok:
            items = response.json().get('items', [])
            if items:
                self.activity_id = items[0]['id']

    @task(8)
    def browse_activities(self):
        self.client.get('/activities?citySettlement=Moscow&limit=30', headers=self.auth_headers, name='Activities / List')
        #self.client.get('/activities/recommended?limit=30', headers=self.auth_headers, name='Activities / Recommended')
        if self.activity_id:
            self.client.get(f'/activities/{self.activity_id}', headers=self.auth_headers, name='Activities / Detail')

    @task(5)
    def profile_and_social(self):
        self.client.get('/me', headers=self.auth_headers, name='Users / Me')
        if self.other_user_id:
            self.client.get(f'/users/{self.other_user_id}', headers=self.auth_headers, name='Users / Detail')
        self.client.get('/me/subscriptions?limit=30', headers=self.auth_headers, name='Subscriptions / List')

    @task(4)
    def participation_flow(self):
        if not self.activity_id:
            return
        with self.client.post(
            f'/activities/{self.activity_id}/join',
            headers=self.auth_headers,
            name='Participation / Join',
            catch_response=True,
        ) as response:
            if response.status_code in (204, 400):
                response.success()
        self.client.get(
            f'/activities/{self.activity_id}/participants?limit=30',
            headers=self.auth_headers,
            name='Participation / Participants',
        )

    @task(3)
    def saved_and_notifications(self):
        if self.activity_id:
            with self.client.post(
                f'/me/saved-activities/{self.activity_id}',
                headers=self.auth_headers,
                name='Activities / Save',
                catch_response=True,
            ) as response:
                if response.status_code in (204, 400):
                    response.success()
        self.client.get('/me/saved-activities?limit=30', headers=self.auth_headers, name='Activities / Saved list')
        self.client.get('/me/notifications?limit=30', headers=self.auth_headers, name='Notifications / List')
        self.client.post('/notifications/read-all', headers=self.auth_headers, name='Notifications / Read all')

    @task(1)
    def qr_and_rating_flow(self):
        response = self.client.post('/me/qr-token', headers=self.auth_headers, name='Users / QR token')
        if response.ok:
            self.qr_token = response.json()['token']
        if self.activity_id:
            with self.client.post(
                f'/activities/{self.activity_id}/ratings',
                headers=self.auth_headers,
                json={'rating': 5, 'comment': 'loadtest rating attempt'},
                name='Ratings / Create expected guarded',
                catch_response=True,
            ) as response:
                if response.status_code in (201, 400, 403):
                    response.success()

    @task(1)
    def refresh_token_flow(self):
        if not self.refresh_token:
            return
        response = self.client.post(
            '/auth/refresh',
            json={'refreshToken': self.refresh_token},
            name='Auth / Refresh',
        )
        if response.ok:
            data = response.json()
            self.access_token = data['accessToken']
            self.refresh_token = data['refreshToken']
