# Generated by Django 6.0.4 on 2026-05-15 19:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('notifications', '0003_notification_notificatio_user_id_611c58_idx_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='notification',
            old_name='request_user',
            new_name='actor_user',
        ),
        migrations.RemoveField(
            model_name='notification',
            name='activity_title',
        ),
        migrations.AlterField(
            model_name='notification',
            name='type',
            field=models.CharField(choices=[('join_request', 'Join Request'), ('join_request_approved', 'Join Request Approved'), ('join_request_rejected', 'Join Request Rejected'), ('activity_reminder', 'Activity Reminder'), ('new_activity', 'New Activity'), ('activity_cancelled', 'Activity Cancelled'), ('organizer_assigned', 'Organizer Assigned'), ('rate_activity', 'Rate Activity'), ('new_review', 'New Review')], max_length=30),
        ),
    ]
