# Generated by Django 6.0.4 on 2026-05-08 14:37

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('activities', '0005_activity_activities_status_c2e099_idx_and_more'),
        ('participation', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddIndex(
            model_name='participation',
            index=models.Index(fields=['user', 'status'], name='participati_user_id_02d1f0_idx'),
        ),
        migrations.AddIndex(
            model_name='participation',
            index=models.Index(fields=['activity', 'status'], name='participati_activit_df55d8_idx'),
        ),
    ]
